### ISSUE TITLE
Make the first commit :D

### ISSUE THREAD

**Issue by collinsnji** [Nerd-Inc/MedKit#1]
Since, there isn't any data yet for parsing or compressing. I'm idle right now
The person with the first commit, gets a bonus lol (initial commit excluded)

**Comment by sherlockwisdom** [comment]
Aight... gimme my bonus xd

**Comment by sherlockwisdom** [comment]
Can you parse through HTML code and extract data?

**Comment by collinsnji** [comment]
Telegram :D

**Comment by collinsnji** [comment]
I think this issue can be closed now :smile:
